{{- include "pinglib.configmap" (list . "pingdirectory") -}}



{{- define "pingdirectory.configmap" -}}
{{- $top := index . 0 -}}
{{- $v := index . 1 -}}
data:
  ORCHESTRATION_TYPE: KUBERNETES
  K8S_STATEFUL_SET_NAME: {{ include "pinglib.fullname" . }}
  K8S_STATEFUL_SET_SERVICE_NAME: {{ include "pinglib.fullclusterservicename" . }}
{{- end -}}